name: camschool_baas_flutter
description: Complete Client SDK for CamSchool BaaS (Backend-as-a-Service) providing Firestore-like NoSQL database, phone & email Auth, Storage and Push Notifications.
version: 1.0.0
homepage: https://camschool.cm
repository: https://github.com/camschool/baas-flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
